name: yet-another-sort
base: core22
adopt-info: yet-another-sort
license: Apache-2.0
source-code: https://github.com/nicolasbock/yet-another-sort
issues: https://github.com/nicolasbock/yet-another-sort/issues
icon: sort-icon.png

summary: A sort util that mimics the functionality of GNU `sort`
description: |
  **Introction**

  This project leans heavily on, and aspires to eventually reach full feature
  parity with, GNU `sort`. The goal of this project is to experiment with
  additional features that are not part of GNU `sort`.

  The main purpose of this program is to write sorted concatenation of all
  file(s) to standard output.

  **Multiline Support**

  The user can specify how many lines `yet-another-sort` should consider as one
  `multiline` unit. For example, using the following input:

      b
      1
      a
      2

  can be sorted 2 lines at a time with

      $ yet-another-sort --multiline 2
      a
      2
      b
      1

grade: stable
confinement: strict

apps:
  yet-another-sort:
    command: usr/bin/yet-another-sort
    completer: usr/share/yet-another-sort/yet-another-sort-bash-completion.sh

    plugs:
      - home
      - removable-media

parts:
  yet-another-sort:
    plugin: dump
    source: .
    build-snaps:
      - go
    override-build: |
      set -e -u -x
      VERSION=$(git describe --tags)
      craftctl set version=${VERSION}
      make
      install --mode 0755 -D yet-another-sort ${CRAFT_PART_INSTALL}/usr/bin/yet-another-sort
      install --mode 0644 -D scripts/yet-another-sort-bash-completion.sh ${CRAFT_PART_INSTALL}/usr/share/yet-another-sort/yet-another-sort-bash-completion.sh
