name: yet-another-sort
base: core22
adopt-info: yet-another-sort
license: Apache-2.0
source-code: https://github.com/nicolasbock/yet-another-sort

summary: A sort util that mimics the functionality of GNU sort
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  yet-another-sort:
    command: usr/bin/yet-another-sort
    completer: usr/share/yet-another-sort/yet-another-sort-bash-completion.sh

    plugs:
      - home
      - removable-media

parts:
  yet-another-sort:
    plugin: go
    source: .
    build-snaps:
      - go
    override-build: |
      set -e -u -x
      craftctl set version=$(git describe --tags)
      craftctl default
      install --mode 0644 -D scripts/yet-another-sort-bash-completion.sh ${CRAFT_PART_INSTALL}/usr/share/yet-another-sort/yet-another-sort-bash-completion.sh
    organize:
      bin/yet-another-sort: usr/bin/yet-another-sort
