---

name: Build Debian package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          set -e -u -x
          sudo apt-get install --yes --no-install-recommends \
            devscripts \
            git-build-recipe \
            pbuilder \
            pristine-tar \
            quilt
          sudo apt-get build-dep --yes .

      - name: Build source package
        run: |
          set -e -u -x
          cat > ../recipe <<EOF
          # git-build-recipe format 0.4 deb-version {debupstream}-0~{revtime}
          ${PWD} HEAD
          EOF
          cat ../recipe
          git-build-recipe --allow-fallback-to-native ../recipe build

      - name: Prepare pbuilder
        run: |
          set -e -u -x
          sudo pbuilder create --distribution jammy
          sudo pbuilder --update

      - name: Build binary package
        run: |
          set -e -u -x
          sudo pbuilder build --buildresult result build/*.dsc

      - name: Upload artifacts (source package)
        uses: actions/upload-artifact@v3
        with:
          name: test-build-source-package
          path: build/**

      - name: Upload artifacts (binary package)
        uses: actions/upload-artifact@v3
        with:
          name: test-build-binary-package
          path: result/**
