---

name: Go package build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: make

      - name: Formatting check
        run: |
          set -e -u -x
          gofmt -w *.go
          (( $(git diff | wc -l) == 0 )) || false

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage
