---

name: Go package build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: make

      - name: Formatting check
        run: |
          set -e -u -x
          gofmt -w *.go
          (( $(git diff | wc -l) == 0 )) || false

      - name: Go vet
        run: go vet

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage

      - name: Functional test
        run: |
          set -e -u -x
          ./scripts/generate-random-input-file.py --lines 10 --fields 10 --field-length 4 > input
          cat input
          sort --ignore-case input > sort.output
          ./yet-another-sort --ignore-case input > yas.output
          diff -Naur sort.output yas.output

      - name: Upload artifacts (sort input)
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: functional test data
          path: |
            input
            sort.output
            yas.output
