---
name: Build snap package
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: snapcore/action-build@v1
